// Manually curated data — sourced from Villanelle's Planet Zoo Data Chest spreadsheet.
// Keyed by animal id (snake_case). Applied over auto-extracted ANIMALS entries at init.
// Edit this file to update or add fields that cannot be extracted from game files.

const MANUAL_DATA = {
  'aardvark': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Djibouti','Equatorial Guinea','Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Kenya','Liberia','Malawi','Mali','Mauritania','Mozambique','Namibia','Niger','Nigeria','Rwanda','Senegal','Sierra Leone','Somalia','South Africa','South Sudan','Tanzania','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Nocturnal'},
  'addax': {regions:['Niger','Chad'],sleepingPattern:'Nocturnal'},
  'african_buffalo': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Equatorial Guinea','Ethiopia','Gabon','Ghana','Guinea','Guinea-Bissau','Kenya','Liberia','Malawi','Mali','Mozambique','Namibia','Niger','Nigeria','Rwanda','Senegal','Sierra Leone','Somalia','South Africa','South Sudan','Sudan','Tanzania','Togo','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Diurnal'},
  'african_crested_porcupine': {regions:['Italy','Morocco','Algeria','Tunisia','Libya','Senegal','Gambia','Guinea-Bissau','Guinea','Sierra Leone','Liberia',"Côte d'Ivoire",'Burkina Faso','Ghana','Togo','Benin','Nigeria','Cameroon','Chad','Central African Republic','South Sudan','Ethiopia','Democratic Republic of the Congo','Uganda','Rwanda','Burundi','Tanzania'],sleepingPattern:'Nocturnal'},
  'african_leopard': {regions:['Benin','Burkina Faso',"Côte d'Ivoire",'Ghana','Guinea','Guinea-Bissau','Niger','Nigeria','Senegal','Liberia','Sierra Leone','Gambia','Mali'],sleepingPattern:'Nocturnal'},
  'african_penguin': {regions:['Namibia','South Africa'],sleepingPattern:'Crepuscular'},
  'african_savannah_elephant': {regions:['Kenya','Tanzania','Botswana','Zimbabwe','Namibia','Angola'],sleepingPattern:'Diurnal'},
  'african_spurred_tortoise': {regions:['Mauritania','Senegal','Mali','Burkina Faso','Niger','Nigeria','Cameroon','Chad','Central African Republic','Sudan','Eritrea','Ethiopia','Djibouti','Yemen'],sleepingPattern:'Diurnal'},
  'african_wild_dog': {regions:['Angola','Botswana','Central African Republic','Ethiopia','Kenya','Mozambique','Namibia','Senegal','South Africa','South Sudan','Tanzania','Zambia','Zimbabwe','Algeria','Mali'],sleepingPattern:'Diurnal'},
  'aldabra_giant_tortoise': {regions:['Seychelles'],sleepingPattern:'Diurnal'},
  'alpaca': {regions:['Peru','Bolivia','Chile'],sleepingPattern:'Diurnal'},
  'alpine_goat': {regions:['France','Italy','Switzerland'],sleepingPattern:'Diurnal'},
  'alpine_ibex': {regions:['France','Switzerland','Italy','Austria','Germany','Slovenia'],sleepingPattern:'Diurnal'},
  'american_alligator': {regions:['USA','Mexico'],sleepingPattern:'Nocturnal'},
  'american_bison': {regions:['Canada','USA'],sleepingPattern:'Crepuscular'},
  'american_flamingo': {regions:['USA','Cuba','Mexico','Venezuela','Caribbean','Ecuador','Dominican Republic','Colombia'],sleepingPattern:'Diurnal'},
  'american_standard_donkey': {regions:['Canada','USA','Mexico'],sleepingPattern:'Diurnal'},
  'amur_leopard': {regions:['Russia','China'],sleepingPattern:'Nocturnal'},
  'arctic_fox': {regions:['Canada','USA','Greenland','Iceland','Finland','Norway','Sweden'],sleepingPattern:'Diurnal'},
  'arctic_wolf': {regions:['Canada','Greenland'],sleepingPattern:'Crepuscular'},
  'asian_small_clawed_otter': {regions:['India','Bangladesh','China','Laos','Thailand','Vietnam','Cambodia','Malaysia','Indonesia','Philippines','Nepal','Bhutan','Myanmar','Brunei'],sleepingPattern:'Diurnal'},
  'asian_water_monitor': {regions:['India','Sri Lanka','Bangladesh','Myanmar','Thailand','Laos','Vietnam','China','Cambodia','Malaysia','Indonesia','Brunei'],sleepingPattern:'Diurnal'},
  'bactrian_camel': {regions:['Mongolia','China','Himalayas','Siberia','Russia','India','Nepal','Bhutan'],sleepingPattern:'Diurnal'},
  'bairds_tapir': {regions:['Belize','Colombia','Costa Rica','Guatemala','Honduras','Mexico','Nicaragua','Panama'],sleepingPattern:'Nocturnal'},
  'bengal_tiger': {regions:['India','Bangladesh','Nepal','Bhutan','China','Myanmar'],sleepingPattern:'Nocturnal'},
  'bighorn_sheep': {regions:['Canada','USA','Mexico'],sleepingPattern:'Diurnal'},
  'binturong': {regions:['Philippines','Bhutan','Thailand','Malaysia','Indonesia','Brunei','Singapore','Laos','Vietnam','Myanmar','Cambodia','Bangladesh','China','India','Nepal'],sleepingPattern:'Nocturnal'},
  'black_and_white_ruffed_lemur': {regions:['Madagascar'],sleepingPattern:'Cathemeral'},
  'black_rhinoceros': {regions:['Kenya','Rwanda','Tanzania','Angola','Zambia','Malawi','Mozambique','Namibia','Botswana','Zimbabwe','South Africa','Eswatini'],sleepingPattern:'Diurnal'},
  'black_tailed_prairie_dog': {regions:['Canada','USA','Mexico'],sleepingPattern:'Crepuscular'},
  'black_wildebeest': {regions:['South Africa','Eswatini','Lesotho','Namibia'],sleepingPattern:'Cathemeral'},
  'blackbuck': {regions:['India','Nepal','Pakistan','Bangladesh'],sleepingPattern:'Diurnal'},
  'blue_wildebeest': {regions:['Kenya','Tanzania','Angola','Zambia','Namibia','Botswana','Zimbabwe','Mozambique','South Africa','Eswatini'],sleepingPattern:'Cathemeral'},
  'bongo': {regions:['Cameroon','Central African Republic','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Equatorial Guinea','Gabon','Ghana','Liberia','Sierra Leone','South Sudan'],sleepingPattern:'Nocturnal'},
  'bonobo': {regions:['Democratic Republic of the Congo'],sleepingPattern:'Diurnal'},
  'bornean_elephant': {regions:['Borneo','Indonesia','Malaysia'],sleepingPattern:'Diurnal'},
  'bornean_orangutan': {regions:['Borneo','Malaysia','Indonesia'],sleepingPattern:'Diurnal'},
  'bush_dog': {regions:['Ecuador','Colombia','Venezuela','Costa Rica','Guyana','Suriname','French Guiana','Brazil','Peru','Bolivia','Paraguay'],sleepingPattern:'Diurnal'},
  'california_sea_lion': {regions:['USA','Mexico','Guatemala','El Salvador','Honduras','Nicaragua','Costa Rica'],sleepingPattern:'Diurnal'},
  'capybara': {regions:['Venezuela','Colombia','Peru','Bolivia','Brazil','Argentina','Guyana','Ecuador','Paraguay','Uruguay','Suriname','French Guiana'],sleepingPattern:'Crepuscular'},
  'caracal': {regions:['Morocco','Algeria','Egypt','Mali','Niger','Chad','Sudan','South Sudan','Ethiopia','Senegal','Gambia','Guinea-Bissau','Guinea','Burkina Faso',"Côte d'Ivoire",'Ghana','Togo','Benin','Nigeria','Cameroon','Central African Republic','Uganda','Kenya','Somalia','Tanzania','Democratic Republic of the Congo','Angola','Zambia','Malawi','Namibia','Botswana','Zimbabwe','Mozambique','South Africa','Lesotho','Eswatini','Türkiye','Lebanon','Syria','Israel','Jordan','Saudi Arabia','Yemen','Oman','Iraq','Iran','Kazakhstan','Turkmenistan','Uzbekistan','Afghanistan','Pakistan','India'],sleepingPattern:'Cathemeral'},
  'cheetah': {regions:['Niger','Sudan','Ethiopia','Kenya','Tanzania','Namibia','Botswana','Iran'],sleepingPattern:'Diurnal'},
  'chinese_pangolin': {regions:['India','Nepal','Bhutan','Bangladesh','Myanmar','China','Taiwan'],sleepingPattern:'Nocturnal'},
  'clouded_leopard': {regions:['Malaysia','Thailand','Cambodia','Vietnam','Laos','Myanmar','China','Nepal','Bhutan','Bangladesh','India'],sleepingPattern:'Nocturnal'},
  'collared_peccary': {regions:['USA','Mexico','Guatemala','Belize','Honduras','Nicaragua','Costa Rica','Panama','Colombia','Venezuela','Ecuador','Peru','Bolivia','Brazil','Paraguay','Argentina'],sleepingPattern:'Cathemeral'},
  'colombian_white_faced_capuchin_monkey': {regions:['Panama','Colombia','Ecuador'],sleepingPattern:'Diurnal'},
  'common_ostrich': {regions:['Algeria','Angola','Botswana','Burkina Faso','Cameroon','Central African Republic','Chad','Djibouti','Egypt','Eritrea','Ethiopia','Kenya','Mali','Mauritania','Mozambique','Namibia','Niger','Nigeria','Senegal','South Africa','South Sudan','Sudan','Tanzania','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Diurnal'},
  'common_warthog': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Democratic Republic of the Congo',"Côte d'Ivoire",'Djibouti','Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Kenya','Liberia','Malawi','Mali','Mauritania','Mozambique','Namibia','Niger','Nigeria','Rwanda','Senegal','Sierra Leone','South Africa','South Sudan','Sudan','Tanzania','Togo','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Diurnal'},
  'common_wombat': {regions:['Australia'],sleepingPattern:'Nocturnal'},
  'coquerels_sifaka': {regions:['Madagascar'],sleepingPattern:'Diurnal'},
  'cougar': {regions:['Canada','USA','Mexico','Guatemala','Belize','El Salvador','Honduras','Nicaragua','Costa Rica','Panama','Colombia','Venezuela','Guyana','Suriname','French Guiana','Ecuador','Peru','Bolivia','Paraguay','Brazil','Chile','Argentina','Uruguay'],sleepingPattern:'Cathemeral'},
  'coyote': {regions:['Canada','USA','Mexico','Belize','El Salvador','Guatemala','Honduras','Nicaragua','Costa Rica','Panama'],sleepingPattern:'Crepuscular'},
  'cuviers_dwarf_caiman': {regions:['Bolivia','Brazil','Colombia','Ecuador','French Guiana','Guyana','Paraguay','Peru','Suriname','Venezuela'],sleepingPattern:'Crepuscular'},
  'dall_sheep': {regions:['USA','Canada'],sleepingPattern:'Diurnal'},
  'dama_gazelle': {regions:['Morocco','Mali','Algeria','Niger','Chad'],sleepingPattern:'Diurnal'},
  'dhole': {regions:['China','India','Malaysia','Thailand','Mongolia','Russia','Vietnam','Cambodia','Laos','Myanmar','Bangladesh','Bhutan','Nepal'],sleepingPattern:'Crepuscular'},
  'dingo': {regions:['Australia'],sleepingPattern:'Crepuscular'},
  'dromedary_camel': {regions:['Morocco','Algeria','Tunisia','Libya','Egypt','Mauritania','Mali','Niger','Chad','Sudan','Eritrea','Senegal','Gambia','Guinea-Bissau','Guinea','Sierra Leone','Liberia',"Côte d'Ivoire",'Burkina Faso','Ghana','Togo','Benin','Nigeria','South Sudan','Ethiopia','Djibouti','Kenya','Somalia','Israel','Jordan','Saudi Arabia','Yemen','Oman','United Arab Emirates','Qatar','Bahrain','Kuwait','Lebanon','Syria','Iraq','Türkiye','Iran','Turkmenistan','Tajikistan','Afghanistan','Pakistan'],sleepingPattern:'Diurnal'},
  'emu': {regions:['Australia'],sleepingPattern:'Diurnal'},
  'eurasian_lynx': {regions:['France','Switzerland','Italy','Austria','Germany','Norway','Sweden','Finland','Russia','Estonia','Latvia','Lithuania','Belarus','Poland','Czechia','Slovakia','Ukraine','Hungary','Romania','Slovenia','Bosnia and Herzegovina','Serbia','Montenegro','Bulgaria','Albania','North Macedonia','Türkiye','Georgia','Armenia','Azerbaijan','Iran','Afghanistan','Uzbekistan','Tajikistan','Kyrgyzstan','Kazakhstan','Pakistan','India','Nepal','Bhutan','China','Mongolia'],sleepingPattern:'Nocturnal'},
  'european_badger': {regions:['United Kingdom','England','Scotland','Wales','Portugal','Spain','France','Luxembourg','Belgium','Netherlands','Italy','Switzerland','Austria','Germany','Denmark','Norway','Sweden','Poland','Czechia','Slovakia','Hungary','Slovenia','Croatia','Bosnia and Herzegovina','Montenegro','Serbia','Kosovo','Bulgaria','Romania','Ukraine','Belarus','Lithuania','Latvia','Estonia','Finland','Russia','Georgia','Türkiye','Armenia','Azerbaijan','Syria','Lebanon','Israel','Jordan','Iraq','Iran','Turkmenistan','Afghanistan','Tajikistan'],sleepingPattern:'Nocturnal'},
  'european_fallow_deer': {regions:['United Kingdom','England','Scotland','Wales','Portugal','Spain','France','Luxembourg','Belgium','Netherlands','Italy','Switzerland','Austria','Germany','Denmark','Norway','Sweden','Poland','Czechia','Slovakia','Hungary','Slovenia','Croatia','Bosnia and Herzegovina','Montenegro','Serbia','Kosovo','Bulgaria','Romania','Ukraine','Belarus','Lithuania','Latvia'],sleepingPattern:'Crepuscular'},
  'fennec_fox': {regions:['Morocco','Algeria','Tunisia','Libya','Egypt','Western Sahara','Mauritania','Mali','Niger','Chad','Sudan'],sleepingPattern:'Nocturnal'},
  'formosan_black_bear': {regions:['Taiwan'],sleepingPattern:'Nocturnal'},
  'fossa': {regions:['Madagascar'],sleepingPattern:'Cathemeral'},
  'galapagos_giant_tortoise': {regions:['Galapagos Islands','Ecuador'],sleepingPattern:'Diurnal'},
  'gemsbok': {regions:['Namibia','Botswana','South Africa'],sleepingPattern:'Diurnal'},
  'gharial': {regions:['Bangladesh','Nepal','India'],sleepingPattern:'Diurnal'},
  'giant_anteater': {regions:['Honduras','Nicaragua','Costa Rica','Panama','Colombia','Venezuela','Ecuador','Guyana','Suriname','French Guiana','Brazil','Argentina','Peru','Bolivia','Paraguay'],sleepingPattern:'Nocturnal'},
  'giant_otter': {regions:['Bolivia','Brazil','Colombia','Ecuador','French Guiana','Guyana','Paraguay','Peru','Suriname','Venezuela'],sleepingPattern:'Diurnal'},
  'giant_panda': {regions:['China'],sleepingPattern:'Diurnal'},
  'greater_flamingo': {regions:['Bangladesh','Pakistan','India','Sri Lanka','Türkiye','Israel','Lebanon','United Arab Emirates','Kuwait','Bahrain','Spain','Albania','North Macedonia','Greece','Cyprus','Portugal','Italy'],sleepingPattern:'Diurnal'},
  'greater_rhea': {regions:['Argentina','Bolivia','Brazil','Paraguay','Uruguay'],sleepingPattern:'Diurnal'},
  'grey_seal': {regions:['United Kingdom','England','Scotland','Wales','Ireland','Iceland','Norway','Denmark','France','Netherlands','Belgium','Germany','Sweden','Finland','Estonia','Latvia','Lithuania','Poland','Russia','Canada','USA'],sleepingPattern:'Diurnal'},
  'grizzly_bear': {regions:['Canada','USA'],sleepingPattern:'Diurnal'},
  'hamadryas_baboon': {regions:['Ethiopia','Djibouti','Somalia','Yemen'],sleepingPattern:'Diurnal'},
  'highland_cattle': {regions:['Scotland','United Kingdom','England','Wales'],sleepingPattern:'Diurnal'},
  'hill_radnor_sheep': {regions:['Wales','England','United Kingdom','Scotland'],sleepingPattern:'Diurnal'},
  'himalayan_brown_bear': {regions:['Afghanistan','Pakistan','India','China','Nepal','Kazakhstan'],sleepingPattern:'Crepuscular'},
  'hippopotamus': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Equatorial Guinea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Kenya','Malawi','Mali','Mozambique','Namibia','Niger','Nigeria','Rwanda','Senegal','Sierra Leone','Somalia','South Africa','South Sudan','Sudan','Tanzania','Togo','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Nocturnal'},
  'honey_badger': {regions:['Algeria','Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Djibouti','Equatorial Guinea','Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','India','Iran','Iraq','Israel','Jordan','Kazakhstan','Kenya','Kuwait','Lebanon','Liberia','Malawi','Mali','Mauritania','Morocco','Mozambique','Namibia','Nepal','Niger','Nigeria','Oman','Pakistan','Qatar','Rwanda','Saudi Arabia','Senegal','Sierra Leone','Somalia','South Africa','Sudan','Tanzania','Togo','Turkmenistan','Uganda','United Arab Emirates','Uzbekistan','Western Sahara','Yemen','Zambia','Zimbabwe'],sleepingPattern:'Diurnal'},
  'indian_elephant': {regions:['India','Nepal','Bangladesh','Bhutan','Myanmar','Thailand','Malaysia','Laos','China','Cambodia','Vietnam'],sleepingPattern:'Crepuscular'},
  'indian_peafowl': {regions:['Bangladesh','Bhutan','India','Nepal','Pakistan','Sri Lanka'],sleepingPattern:'Diurnal'},
  'indian_rhinoceros': {regions:['Nepal','India','Bhutan'],sleepingPattern:'Crepuscular'},
  'jaguar': {regions:['Mexico','Colombia','Venezuela','Ecuador','Peru','Bolivia','Paraguay','Uruguay','Brazil','Guyana','Suriname','Panama','Costa Rica','French Guiana','Nicaragua','Honduras','El Salvador','Guatemala','Belize'],sleepingPattern:'Nocturnal'},
  'japanese_macaque': {regions:['Japan'],sleepingPattern:'Diurnal'},
  'japanese_raccoon_dog': {regions:['Japan'],sleepingPattern:'Crepuscular'},
  'king_penguin': {regions:['Argentina','Chile','France','South Africa','Sub-Antarctic & Southern Ocean Islands','Australia','Brazil','New Zealand','Uruguay'],sleepingPattern:'Diurnal'},
  'kirks_dik_dik': {regions:['Uganda','Kenya','Tanzania','Angola','Namibia'],sleepingPattern:'Crepuscular'},
  'koala': {regions:['Australia'],sleepingPattern:'Nocturnal'},
  'komodo_dragon': {regions:['Indonesia'],sleepingPattern:'Diurnal'},
  'lar_gibbon': {regions:['Myanmar','Thailand','Malaysia','Indonesia','China'],sleepingPattern:'Diurnal'},
  'lion_tailed_macaque': {regions:['India'],sleepingPattern:'Diurnal'},
  'little_penguin': {regions:['Australia','New Zealand'],sleepingPattern:'Diurnal'},
  'llama': {regions:['Ecuador','Peru','Bolivia','Chile','Argentina'],sleepingPattern:'Diurnal'},
  'malayan_tapir': {regions:['Malaysia','Indonesia','Thailand'],sleepingPattern:'Crepuscular'},
  'mandrill': {regions:['Cameroon','Gabon','Equatorial Guinea','Congo'],sleepingPattern:'Diurnal'},
  'maned_wolf': {regions:['Bolivia','Brazil','Paraguay','Uruguay','Argentina'],sleepingPattern:'Cathemeral'},
  'markhor': {regions:['Uzbekistan','Turkmenistan','Tajikistan','Afghanistan','Pakistan','India'],sleepingPattern:'Diurnal'},
  'meerkat': {regions:['Angola','Namibia','Botswana','South Africa','Lesotho'],sleepingPattern:'Diurnal'},
  'moose': {regions:['Canada','USA','Norway','Sweden','Finland','Poland','Lithuania','Latvia','Estonia','Belarus','Ukraine','Russia'],sleepingPattern:'Crepuscular'},
  'mute_swan': {regions:['Albania','Austria','Azerbaijan','Belarus','Belgium','Bosnia and Herzegovina','Bulgaria','China','Croatia','Czechia','Denmark','Estonia','Finland','France','Germany','Greece','Hungary','India','Ireland','Israel','Italy','Japan','Latvia','Liechtenstein','Lithuania','Luxembourg','Moldova','Montenegro','Netherlands','North Macedonia','Norway','Pakistan','Poland','Romania','Russia','Serbia','Slovakia','Slovenia','Sweden','Switzerland','Taiwan','Türkiye','Ukraine','United Kingdom','England','Scotland','Wales','Uzbekistan','Kazakhstan','Mongolia','Turkmenistan','Afghanistan','Armenia','Cyprus','Iran','Iraq','South Korea','Kyrgyzstan','Spain','North Korea'],sleepingPattern:'Diurnal'},
  'nile_lechwe': {regions:['South Sudan','Ethiopia'],sleepingPattern:'Crepuscular'},
  'nile_monitor': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Egypt','Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Kenya','Lesotho','Liberia','Malawi','Mali','Mauritania','Mozambique','Namibia','Niger','Nigeria','Rwanda','Senegal','Sierra Leone','Somalia','South Africa','South Sudan','Sudan','Tanzania','Togo','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Diurnal'},
  'nilgai': {regions:['India','Nepal','Bangladesh','Pakistan'],sleepingPattern:'Diurnal'},
  'nine_banded_armadillo': {regions:['USA','Mexico','Argentina','Uruguay','Guatemala','Nicaragua','Costa Rica','Panama','Colombia','Venezuela','Ecuador','Guyana','French Guiana','Peru','Brazil','Bolivia','Paraguay'],sleepingPattern:'Nocturnal'},
  'north_american_beaver': {regions:['Canada','USA','Mexico'],sleepingPattern:'Crepuscular'},
  'north_island_brown_kiwi': {regions:['New Zealand'],sleepingPattern:'Nocturnal'},
  'north_sulawesi_babirusa': {regions:['Indonesia'],sleepingPattern:'Crepuscular'},
  'nyala': {regions:['Malawi','Mozambique','South Africa','Eswatini','Zimbabwe','Botswana','Namibia'],sleepingPattern:'Crepuscular'},
  'ocelot': {regions:['USA','Argentina','Belize','Bolivia','Brazil','Colombia','Costa Rica','Ecuador','El Salvador','French Guiana','Guatemala','Guyana','Honduras','Mexico','Nicaragua','Panama','Paraguay','Peru','Suriname','Trinidad and Tobago','Uruguay','Venezuela'],sleepingPattern:'Nocturnal'},
  'okapi': {regions:['Democratic Republic of the Congo'],sleepingPattern:'Diurnal'},
  'pallass_cat': {regions:['Armenia','Azerbaijan','Iran','Kazakhstan','Uzbekistan','Turkmenistan','Kyrgyzstan','Tajikistan','Afghanistan','Pakistan','Russia','Mongolia','China','Nepal','Bhutan','India'],sleepingPattern:'Crepuscular'},
  'plains_zebra': {regions:['Angola','Botswana','Democratic Republic of the Congo','Eswatini','Ethiopia','Kenya','Malawi','Mozambique','Namibia','Rwanda','South Africa','South Sudan','Tanzania','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Diurnal'},
  'platypus': {regions:['Australia'],sleepingPattern:'Nocturnal'},
  'polar_bear': {regions:['Canada','USA','Greenland','Norway','Russia','Iceland'],sleepingPattern:'Diurnal'},
  'pre_davids_deer': {regions:['China'],sleepingPattern:'Diurnal'},
  'proboscis_monkey': {regions:['Borneo','Indonesia','Malaysia','Brunei'],sleepingPattern:'Diurnal'},
  'pronghorn_antelope': {regions:['USA','Canada','Mexico'],sleepingPattern:'Crepuscular'},
  'przewalskis_horse': {regions:['Mongolia','China','Russia','Kazakhstan','Ukraine','Belarus'],sleepingPattern:'Diurnal'},
  'pygmy_hippopotamus': {regions:['Sierra Leone','Liberia','Guinea',"Côte d'Ivoire"],sleepingPattern:'Nocturnal'},
  'quokka': {regions:['Australia'],sleepingPattern:'Nocturnal'},
  'raccoon': {regions:['Canada','USA','Mexico','Guatemala','Belize','Honduras','El Salvador','Nicaragua','Costa Rica','Panama'],sleepingPattern:'Nocturnal'},
  'red_crowned_crane': {regions:['Japan','South Korea','North Korea','China','Mongolia','Russia'],sleepingPattern:'Diurnal'},
  'red_deer': {regions:['United Kingdom','England','Scotland','Wales','Norway','Sweden','Denmark','Finland','Estonia','Latvia','Lithuania','Russia','Netherlands','Belgium','France','Germany','Poland','Belarus','Czechia','Slovakia','Ukraine','Switzerland','Austria','Hungary','Romania','Moldova','Portugal','Spain','Italy','Bosnia and Herzegovina','Serbia','Bulgaria','Greece','Türkiye','Armenia','Azerbaijan','Georgia','Iran','Morocco','Algeria','Tunisia'],sleepingPattern:'Crepuscular'},
  'red_fox': {regions:['Canada','USA','Morocco','Algeria','Libya','Egypt','Sudan','Albania','Andorra','Austria','Belarus','Belgium','Bosnia and Herzegovina','Bulgaria','Croatia','Cyprus','Czechia','Denmark','Estonia','Finland','France','Germany','Gibraltar','Greece','Hungary','Ireland','Italy','Latvia','Liechtenstein','Lithuania','Luxembourg','Moldova','Monaco','Montenegro','Netherlands','North Macedonia','Norway','Poland','Portugal','Romania','Russia','San Marino','Serbia','Slovakia','Slovenia','Spain','Sweden','Switzerland','Türkiye','Ukraine','United Kingdom','England','Scotland','Wales'],sleepingPattern:'Nocturnal'},
  'red_kangaroo': {regions:['Australia'],sleepingPattern:'Crepuscular'},
  'red_necked_wallaby': {regions:['Australia'],sleepingPattern:'Crepuscular'},
  'red_panda': {regions:['Himalayas','China','India','Nepal','Bhutan'],sleepingPattern:'Nocturnal'},
  'red_river_hog': {regions:['Senegal','Gambia','Mali','Guinea-Bissau','Guinea','Sierra Leone','Liberia',"Côte d'Ivoire",'Ghana','Togo','Benin','Nigeria','Cameroon','Chad','Central African Republic','South Sudan','Equatorial Guinea','Gabon','Congo','Democratic Republic of the Congo','Uganda','Angola','Rwanda','Burundi'],sleepingPattern:'Crepuscular'},
  'red_ruffed_lemur': {regions:['Madagascar'],sleepingPattern:'Cathemeral'},
  'reindeer': {regions:['Russia','Siberia','Canada','USA','Norway','Denmark','Finland','Greenland'],sleepingPattern:'Diurnal'},
  'reticulated_giraffe': {regions:['Somalia','Ethiopia','Kenya'],sleepingPattern:'Diurnal'},
  'ring_tailed_lemur': {regions:['Madagascar'],sleepingPattern:'Cathemeral'},
  'sable_antelope': {regions:['Mozambique','Zimbabwe','Eswatini','Lesotho','Malawi','South Africa','Botswana'],sleepingPattern:'Diurnal'},
  'saiga': {regions:['Mongolia','Kazakhstan','Uzbekistan','Russia'],sleepingPattern:'Diurnal'},
  'saltwater_crocodile': {regions:['Australia','Bangladesh','Brunei','India','Indonesia','Malaysia','Myanmar','Papua New Guinea','Philippines','Singapore','Sri Lanka'],sleepingPattern:'Nocturnal'},
  'sand_cat': {regions:['Morocco','Mauritania','Mali','Algeria','Niger','Chad','Egypt','Israel','Jordan','Saudi Arabia','Yemen','Oman','United Arab Emirates','Qatar','Kuwait','Syria','Iraq','Iran','Afghanistan','Pakistan','Turkmenistan','Uzbekistan','Kazakhstan'],sleepingPattern:'Nocturnal'},
  'scimitar_horned_oryx': {regions:['Morocco','Tunisia','Senegal','Chad','Mauritania','Mali','Algeria','Burkina Faso','Niger','Sudan','Libya','Egypt'],sleepingPattern:'Diurnal'},
  'siamang': {regions:['Indonesia','Malaysia','Thailand'],sleepingPattern:'Diurnal'},
  'siberian_tiger': {regions:['China','Russia','North Korea','Mongolia'],sleepingPattern:'Nocturnal'},
  'sloth_bear': {regions:['India','Nepal','Bhutan'],sleepingPattern:'Nocturnal'},
  'snow_leopard': {regions:['China','Siberia','Himalayas','Mongolia','Russia','India','Nepal','Bhutan'],sleepingPattern:'Crepuscular'},
  'somali_wild_ass': {regions:['Somalia','Djibouti','Sudan','Ethiopia','Eritrea'],sleepingPattern:'Diurnal'},
  'southern_cassowary': {regions:['Australia','Papua New Guinea','Indonesia'],sleepingPattern:'Diurnal'},
  'southern_white_rhinoceros': {regions:['South Africa','Angola','Zambia','Zimbabwe','Malawi','Mozambique','Namibia','Botswana','Lesotho','Eswatini'],sleepingPattern:'Crepuscular'},
  'spectacled_bear': {regions:['Colombia','Ecuador','Peru','Bolivia'],sleepingPattern:'Diurnal'},
  'spectacled_caiman': {regions:['Colombia','Venezuela','Guyana','Suriname','French Guiana','Brazil','Peru','Ecuador','Panama','Costa Rica','Nicaragua','El Salvador','Honduras','Guatemala','Belize','Mexico'],sleepingPattern:'Crepuscular'},
  'spotted_hyena': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Djibouti','Equatorial Guinea','Eritrea','Eswatini','Ethiopia','Gambia','Ghana','Guinea','Guinea-Bissau','Kenya','Malawi','Mali','Mauritania','Mozambique','Namibia','Niger','Nigeria','Rwanda','Senegal','Sierra Leone','Somalia','South Africa','South Sudan','Sudan','Tanzania','Uganda','Zambia','Zimbabwe'],sleepingPattern:'Nocturnal'},
  'springbok': {regions:['Namibia','Botswana','South Africa'],sleepingPattern:'Diurnal'},
  'striped_hyena': {regions:['Morocco','Algeria','Libya','Egypt','Mali','Niger','Chad','Sudan','South Sudan','Ethiopia','Senegal','Burkina Faso','Ghana','Togo','Benin','Nigeria','Cameroon','Central African Republic','Uganda','Kenya','Somalia','Tanzania','Türkiye','Lebanon','Syria','Israel','Jordan','Saudi Arabia','Yemen','Oman','United Arab Emirates','Iraq','Iran','Turkmenistan','Uzbekistan','Afghanistan','Pakistan','India','Nepal'],sleepingPattern:'Nocturnal'},
  'striped_skunk': {regions:['Canada','USA','Mexico'],sleepingPattern:'Nocturnal'},
  'sun_bear': {regions:['Malaysia','Indonesia','Brunei','Thailand','Cambodia','Vietnam','Myanmar','Laos','Bangladesh','India'],sleepingPattern:'Nocturnal'},
  'sussex_chicken': {regions:['England','United Kingdom','Scotland','Wales'],sleepingPattern:'Diurnal'},
  'takin': {regions:['Bhutan','India','Myanmar','China'],sleepingPattern:'Diurnal'},
  'tamworth_pig': {regions:['England','United Kingdom','Scotland','Wales'],sleepingPattern:'Diurnal'},
  'tasmanian_devil': {regions:['Australia'],sleepingPattern:'Nocturnal'},
  'thomsons_gazelle': {regions:['Tanzania','Kenya'],sleepingPattern:'Diurnal'},
  'timber_wolf': {regions:['Afghanistan','Albania','Armenia','Austria','Azerbaijan','Belarus','Belgium','Bhutan','Bosnia and Herzegovina','Bulgaria','Canada','China','Croatia','Czechia','Denmark','Estonia','Finland','France','Georgia','Germany','Greece','Greenland','Hungary','India','Iran','Iraq','Israel','Italy','Jordan','Kazakhstan','North Korea','South Korea','Kyrgyzstan','Latvia','Libya','Lithuania','Luxembourg','Mexico','Moldova','Mongolia','Montenegro','Myanmar','Nepal','Netherlands','North Macedonia','Norway','Oman','Pakistan','Poland','Portugal','Romania','Russia','Saudi Arabia','Serbia','Slovakia','Slovenia','Spain','Sweden','Switzerland','Syria','Tajikistan','Turkmenistan','Türkiye','Ukraine','United Arab Emirates','USA','Uzbekistan','Yemen'],sleepingPattern:'Crepuscular'},
  'west_african_lion': {regions:['Senegal','Mali','Niger'],sleepingPattern:'Cathemeral'},
  'western_chimpanzee': {regions:['Guinea','Senegal','Liberia','Sierra Leone',"Côte d'Ivoire"],sleepingPattern:'Diurnal'},
  'western_lowland_gorilla': {regions:['Angola','Cameroon','Central African Republic','Equatorial Guinea','Gabon','Democratic Republic of the Congo'],sleepingPattern:'Diurnal'},
  'white_faced_saki': {regions:['Brazil','French Guiana','Guyana','Suriname','Venezuela'],sleepingPattern:'Diurnal'},
  'wild_boar': {regions:['Afghanistan','Albania','Algeria','Andorra','Armenia','Austria','Azerbaijan','Bangladesh','Belarus','Belgium','Bhutan','Bosnia and Herzegovina','Bulgaria','Cambodia','China','Croatia','Cyprus','Czechia','Estonia','Finland','France','Corsica','Georgia','Germany','Greece','Hungary','India','Indonesia','Iran','Iraq','Israel','Italy','Japan','Jordan','Kazakhstan','North Korea','South Korea','Kyrgyzstan','Laos','Latvia','Lebanon','Liechtenstein','Lithuania','Luxembourg','Malaysia','Moldova','Monaco','Mongolia','Montenegro','Morocco','Myanmar','Nepal','Netherlands','North Macedonia','Pakistan','Palestine','Poland','Portugal','Romania','Russia','San Marino','Serbia','Slovakia','Slovenia','Spain','Sri Lanka','Switzerland','Syria','Taiwan','Tajikistan','Thailand','Tunisia','Turkmenistan','Türkiye','Ukraine','Uzbekistan','Vietnam','Sweden','United Kingdom','England','Scotland','Wales'],sleepingPattern:'Crepuscular'},
  'wild_water_buffalo': {regions:['India','Nepal','Bhutan','Myanmar','Thailand','Cambodia'],sleepingPattern:'Diurnal'},
  'wisent': {regions:['Germany','Poland','Slovakia','Romania','Bulgaria','Ukraine','Belarus','Lithuania','Latvia','Russia'],sleepingPattern:'Diurnal'},
  'wolverine': {regions:['Norway','Sweden','Finland','Russia','Kazakhstan','Mongolia','China','Canada','USA'],sleepingPattern:'Nocturnal'},
  'amazonian_giant_centipede': {regions:['Caribbean','Brazil','Caribbean','Colombia','Venezuela','Trinidad and Tobago']},
  'american_bullfrog': {regions:['Canada','USA','Mexico']},
  'axolotl': {regions:['Mexico']},
  'boa_constrictor': {regions:['Colombia','Ecuador','Peru','Venezuela','Trinidad and Tobago','Guyana','Suriname','French Guiana','Brazil','Bolivia','Uruguay','Argentina']},
  'brazilian_salmon_pink_tarantula': {regions:['Brazil']},
  'brazilian_wandering_spider': {regions:['Brazil','Colombia','Venezuela','Ecuador','Peru','Bolivia','Paraguay','Argentina']},
  'brown_throated_sloth': {regions:['Honduras','Nicaragua','Costa Rica','Panama','Colombia','Venezuela','Ecuador','Peru','Bolivia','Brazil']},
  'cloudless_sulphur': {regions:['USA','Mexico','Guatemala','Belize','Honduras','Nicaragua','Costa Rica','Panama','Cuba','Caribbean','Dominican Republic','Puerto Rico','Colombia','Venezuela','Ecuador','Peru','Bolivia','Brazil','Paraguay','Uruguay','Chile','Argentina']},
  'common_death_adder': {regions:['Australia']},
  'danube_crested_newt': {regions:['Hungary','Romania','Moldova']},
  'desert_horned_viper': {regions:['Morocco','Algeria','Tunisia','Libya','Egypt','Mauritania','Mali','Niger','Chad','Sudan','Eritrea','Israel','Yemen','Syria']},
  'diamondback_terrapin': {regions:['USA']},
  'eastern_blue_tongued_lizard': {regions:['Australia']},
  'eastern_brown_snake': {regions:['Australia','Papua New Guinea','Indonesia']},
  'egyptian_fruit_bat': {regions:['Türkiye','Cyprus','Syria','Lebanon','Israel','Jordan','Egypt','Senegal','Guinea',"Côte d'Ivoire",'Ghana','Cameroon','Gabon','Congo','Angola','South Africa','Lesotho','Eswatini','Zimbabwe','Mozambique','Malawi','Tanzania','Burundi','Rwanda','Uganda','Kenya','Ethiopia','Yemen','Saudi Arabia','Oman','United Arab Emirates','Iran','Pakistan']},
  'european_peacock': {regions:['Albania','Andorra','Austria','Belarus','Belgium','Bosnia and Herzegovina','Bulgaria','Croatia','Czechia','Denmark','Estonia','Finland','France','Corsica','Germany','Gibraltar','Greece','Hungary','Ireland','Italy','Latvia','Liechtenstein','Lithuania','Luxembourg','Moldova','Montenegro','Netherlands','North Macedonia','Norway','Poland','Portugal','Romania','Russia','San Marino','Serbia','Slovakia','Slovenia','Spain','Sweden','Switzerland','Türkiye','Ukraine','United Kingdom','England','Scotland','Wales','Japan']},
  'fire_salamander': {regions:['Portugal','Spain','France','Luxembourg','Belgium','Netherlands','Germany','Switzerland','Austria','Italy','Czechia','Poland','Slovakia','Ukraine','Romania','Hungary','Slovenia','Croatia','Bosnia and Herzegovina','Serbia','Kosovo','Montenegro','Bulgaria','Albania','North Macedonia','Greece','Türkiye']},
  'giant_burrowing_cockroach': {regions:['Australia']},
  'giant_desert_hairy_scorpion': {regions:['USA','Mexico']},
  'giant_forest_scorpion': {regions:['Sri Lanka','India']},
  'giant_malaysian_leaf_insect': {regions:['Malaysia']},
  'giant_tiger_land_snail': {regions:['Sierra Leone','Liberia',"Côte d'Ivoire",'Togo','Benin','Ghana','Nigeria']},
  'gila_monster': {regions:['Mexico','USA']},
  'golden_poison_frog': {regions:['Colombia']},
  'goliath_beetle': {regions:['Cameroon','Central African Republic','Congo','Gabon','Kenya','Nigeria','Tanzania','Uganda']},
  'goliath_birdeater': {regions:['Suriname','Guyana','French Guiana','Brazil','Venezuela']},
  'goliath_frog': {regions:['Cameroon','Equatorial Guinea']},
  'green_iguana': {regions:['Mexico','Brazil','Ecuador','Caribbean','USA']},
  'hermanns_tortoise': {regions:['Spain','France','Italy','Croatia','Bosnia and Herzegovina','Montenegro','Albania','Serbia','Romania','North Macedonia','Greece','Bulgaria','Türkiye']},
  'lehmanns_poison_frog': {regions:['Colombia']},
  'lesser_antillean_iguana': {regions:['Lesser Antilles','Caribbean']},
  'malabar_rose': {regions:['Sri Lanka']},
  'menelaus_blue_morpho': {regions:['Venezuela','Guyana','Suriname','French Guiana','Brazil','Colombia','Ecuador','Peru','Bolivia','Paraguay']},
  'mexican_red_knee_tarantula': {regions:['Mexico']},
  'monarch': {regions:['Australia','Belize','Caribbean','Brazil','Caribbean','Colombia','Costa Rica','Ecuador','French Guiana','Guatemala','Guyana','Honduras','Mexico','New Zealand','Nicaragua','Panama','Peru','Puerto Rico','Suriname','Trinidad and Tobago','USA','Venezuela','Canada','Belgium','Bhutan','Cambodia','China','Denmark','France','India','Ireland','Italy','Kazakhstan','Kyrgyzstan','Malaysia','Nepal','Sweden','United Kingdom','England','Scotland','Wales','Morocco','Philippines','Portugal','Spain','Taiwan']},
  'old_world_swallowtail': {regions:['Albania','Algeria','Bosnia and Herzegovina','Croatia','Cyprus','Egypt','France','Greece','Israel','Italy','Jordan','Lebanon','Libya','Malta','Montenegro','Morocco','North Macedonia','Palestine','Portugal','Slovenia','Spain','Syria','Tunisia','Türkiye','USA','Canada']},
  'puff_adder': {regions:['Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon','Central African Republic','Chad','Congo','Democratic Republic of the Congo',"Côte d'Ivoire",'Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Kenya','Lesotho','Malawi','Mali','Mauritania','Morocco','Mozambique','Namibia','Niger','Nigeria','Oman','Rwanda','Saudi Arabia','Senegal','Sierra Leone','Somalia','South Africa','Tanzania','Togo','Uganda','Western Sahara','Yemen','Zambia','Zimbabwe']},
  'red_eyed_tree_frog': {regions:['Mexico','Guatemala','Honduras','Nicaragua','Costa Rica','Panama','Colombia']},
  'sacred_scarab_beetle': {regions:['Morocco','Western Sahara','Algeria','Tunisia','Libya','Egypt','Saudi Arabia','Israel','Lebanon','Syria','Italy','France']},
  'spectacled_flying_fox': {regions:['Australia','Papua New Guinea','Indonesia']},
  'titan_beetle': {regions:['Venezuela','Colombia','Ecuador','Peru','Guyana','Brazil','Suriname','French Guiana']},
  'western_diamondback_rattlesnake': {regions:['USA','Mexico']},
  'yellow_anaconda': {regions:['Paraguay','Bolivia','Argentina','Brazil']},
};
